### ISSUE TITLE
Environment under which BTG runs.

### ISSUE THREAD

**Issue by gjahchan** [conix-security/BTG#21]
I have tried to run BTG using Python v2.7.14 on Debian 8 and Python v3.6.3 on CentOS 6. It resulted in lots of errors in both cases.

Rather than waste time fixing the code, I want to try to run it in an environment that is known to work (similar to the development environment).

What environment was BTG designed to run under? (Operating system flavor/version and Python version)?

Thank you in advance for an early response.

Attached are the error logs in both cases.

[Errors-on-CentOS6.9-Python3.6.3.txt](https://github.com/conix-security/BTG/files/1525838/Errors-on-CentOS6.9-Python3.6.3.txt)
[Errors-on-Debian8-Python2.7.14.txt](https://github.com/conix-security/BTG/files/1525839/Errors-on-Debian8-Python2.7.14.txt)

**Comment by rmarsollier** [comment]
Hi,

BTG is not python3 compatible yet, this is a something coming around Q2 2018 ;)

It is supposed to work quite easily on a Debian tho. You problem lies within the installation of the validators pypi package, try installing it from git : https://github.com/kvesteri/validators

**Comment by rmarsollier** [comment]
I just tested on a fresh Debian 9 with python 2.7.13 to be sure, and on Ubuntu (various versions), it works pretty well out of the box with the default config file.
